import { GoogleGenerativeAI, Part } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export const generateLogo = async (base64Sketch: string) => {
  const model = genAI.getGenerativeModel({
    model: "gemini-2.0-flash-exp-image-generation",
  });

  const generationConfig = {
    temperature: 1,
    topP: 0.95,
    topK: 40,
    maxOutputTokens: 8192,
    responseModalities: ["image"],
  };

  try {
    const chatSession = model.startChat({ generationConfig, history: [] });

    // this is the prompt and the sketch
    const result = await chatSession.sendMessage([
      { text: "Generate a professional logo based on this sketch." },
      { inlineData: { data: base64Sketch, mimeType: "image/png" } },
    ] as Part[]);

    // this is the extract AI-generated image
    const candidates = result.response.candidates;
    for (const candidate of candidates || []) {
      for (const part of candidate.content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by AI");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw new Error("AI logo generation failed");
  }
};
